### ISSUE TITLE
Design Docs Checklist

### ISSUE THREAD

**Issue by taylormusolf** [loFiWaterCat/stack-underflow#1]
# Wiki Home Page
- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
  - [x] each wiki page is listed in bullet points
  - [x] all links route the correct page
## Comments
---
# MVP List
- [x] Should have 7 MVPs.
  - [x] 3 of those are User Auth, Heroku, and Production README.
  - [x] The other 4 are from your MPV list
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one full CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
  - [x] MVPs are listed in an ordered list
  - [x] Each MVP is broken down into bullet points
## Comments
- I think you should have answers/comments as its own feature(separate it from your 3 and 4 feature).  I would then push Dashboard and Profile to be a bonus feature
- Add dates to your features so you have a gauge on the timeline you are creating
---
# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
  - [x] primary key
  - [x] not null
  - [x] unique
  - [x] indexed
  - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
 - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
  - [x] schema is written in a table format
  - [x] the table's name are lowercased, snake_cased and `back_ticked`
  - [x] the table header column names are bolded
  - [x] columns names are lowercased and snaked_cased and `back_ticked`
## Comments
- all id's, primary and foreign, should be the type of bigint
- for comments you will need a way to distinguish a comment that is an "answer" versus a comment to an "answer".  You could go off of if if has a `comment_id` or not.  Definitely recommend removing `not null` from `comment_id`.
- I just noticed on SO that you can comment a question vs answer a question.  May want to consider that on how you construct this.  You could maybe do questions and answers as one table where questions have a null foreign key reference to a question but answers do.  Then you could keep comments as something that could be attached to a question or an answer.
- Also generally you do not want `unique: true` on foreign keys as you would want the ability for that owner to own many of that thing not just one.
---
# Sample State
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
  - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
  - [x] Top level slices
    - [x] `entities`
    - [x] `session`
    - [x] `errors` (here or in `ui`)
    - [x] `ui` (if needed)
  - [x] Should NOT have nested slices, aka `comments` inside of `posts`
   + Some info from other tables is ok, for instance:
    + the author username and imageurl for a post. basically any info that the user can't change
    + like count and a boolean on whether the user likes the post instead of a likes slice
## Comments
 - keys need to be camelCased
 - missing some closing brackets and commas
---
# Backend Routes
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
  + probably doesn't need a `GET likes` api endpoint because that info comes through the post show
## Comments
---
# Frontend Routes
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
  - [x] Routes are displayed with `inline coding text` (backticks)
## Comments
